/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';


import {
  AppHome as AppHome
} from './components/app/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLStencilElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  MyApp as MyApp
} from './components/app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLStencilElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  PageTabs as PageTabs
} from './components/app/page-tabs';

declare global {
  interface HTMLPageTabsElement extends PageTabs, HTMLStencilElement {
  }
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };
  interface HTMLElementTagNameMap {
    'page-tabs': HTMLPageTabsElement;
  }
  interface ElementTagNameMap {
    'page-tabs': HTMLPageTabsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'page-tabs': JSXElements.PageTabsAttributes;
    }
  }
  namespace JSXElements {
    export interface PageTabsAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  AppLogin as AppLogin
} from './components/auth/app-login';

declare global {
  interface HTMLAppLoginElement extends AppLogin, HTMLStencilElement {
  }
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };
  interface HTMLElementTagNameMap {
    'app-login': HTMLAppLoginElement;
  }
  interface ElementTagNameMap {
    'app-login': HTMLAppLoginElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-login': JSXElements.AppLoginAttributes;
    }
  }
  namespace JSXElements {
    export interface AppLoginAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  LogoutButton as LogoutButton
} from './components/auth/logout-button';

declare global {
  interface HTMLLogoutButtonElement extends LogoutButton, HTMLStencilElement {
  }
  var HTMLLogoutButtonElement: {
    prototype: HTMLLogoutButtonElement;
    new (): HTMLLogoutButtonElement;
  };
  interface HTMLElementTagNameMap {
    'logout-button': HTMLLogoutButtonElement;
  }
  interface ElementTagNameMap {
    'logout-button': HTMLLogoutButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'logout-button': JSXElements.LogoutButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface LogoutButtonAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  LoadingSpinner as LoadingSpinner
} from './components/common/loading-spinner';

declare global {
  interface HTMLLoadingSpinnerElement extends LoadingSpinner, HTMLStencilElement {
  }
  var HTMLLoadingSpinnerElement: {
    prototype: HTMLLoadingSpinnerElement;
    new (): HTMLLoadingSpinnerElement;
  };
  interface HTMLElementTagNameMap {
    'loading-spinner': HTMLLoadingSpinnerElement;
  }
  interface ElementTagNameMap {
    'loading-spinner': HTMLLoadingSpinnerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'loading-spinner': JSXElements.LoadingSpinnerAttributes;
    }
  }
  namespace JSXElements {
    export interface LoadingSpinnerAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  MorePopoverButton as MorePopoverButton
} from './components/common/more-popover-button';

declare global {
  interface HTMLMorePopoverButtonElement extends MorePopoverButton, HTMLStencilElement {
  }
  var HTMLMorePopoverButtonElement: {
    prototype: HTMLMorePopoverButtonElement;
    new (): HTMLMorePopoverButtonElement;
  };
  interface HTMLElementTagNameMap {
    'more-popover-button': HTMLMorePopoverButtonElement;
  }
  interface ElementTagNameMap {
    'more-popover-button': HTMLMorePopoverButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'more-popover-button': JSXElements.MorePopoverButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface MorePopoverButtonAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  MorePopover as MorePopover
} from './components/common/more-popover';

declare global {
  interface HTMLMorePopoverElement extends MorePopover, HTMLStencilElement {
  }
  var HTMLMorePopoverElement: {
    prototype: HTMLMorePopoverElement;
    new (): HTMLMorePopoverElement;
  };
  interface HTMLElementTagNameMap {
    'more-popover': HTMLMorePopoverElement;
  }
  interface ElementTagNameMap {
    'more-popover': HTMLMorePopoverElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'more-popover': JSXElements.MorePopoverAttributes;
    }
  }
  namespace JSXElements {
    export interface MorePopoverAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  PropertyPopoverButton as PropertyPopoverButton
} from './components/common/property-popover-button';

declare global {
  interface HTMLPropertyPopoverButtonElement extends PropertyPopoverButton, HTMLStencilElement {
  }
  var HTMLPropertyPopoverButtonElement: {
    prototype: HTMLPropertyPopoverButtonElement;
    new (): HTMLPropertyPopoverButtonElement;
  };
  interface HTMLElementTagNameMap {
    'property-popover-button': HTMLPropertyPopoverButtonElement;
  }
  interface ElementTagNameMap {
    'property-popover-button': HTMLPropertyPopoverButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'property-popover-button': JSXElements.PropertyPopoverButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface PropertyPopoverButtonAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  PropertyPopover as PropertyPopover
} from './components/common/property-popover';

declare global {
  interface HTMLPropertyPopoverElement extends PropertyPopover, HTMLStencilElement {
  }
  var HTMLPropertyPopoverElement: {
    prototype: HTMLPropertyPopoverElement;
    new (): HTMLPropertyPopoverElement;
  };
  interface HTMLElementTagNameMap {
    'property-popover': HTMLPropertyPopoverElement;
  }
  interface ElementTagNameMap {
    'property-popover': HTMLPropertyPopoverElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'property-popover': JSXElements.PropertyPopoverAttributes;
    }
  }
  namespace JSXElements {
    export interface PropertyPopoverAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  LazyImg as LazyImg
} from './components/lazy-img/lazy-img';

declare global {
  interface HTMLLazyImgElement extends LazyImg, HTMLStencilElement {
  }
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'src'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
    }
  }
}


import {
  AddProperty as AddProperty
} from './components/properties/add-property';

declare global {
  interface HTMLAddPropertyElement extends AddProperty, HTMLStencilElement {
  }
  var HTMLAddPropertyElement: {
    prototype: HTMLAddPropertyElement;
    new (): HTMLAddPropertyElement;
  };
  interface HTMLElementTagNameMap {
    'add-property': HTMLAddPropertyElement;
  }
  interface ElementTagNameMap {
    'add-property': HTMLAddPropertyElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'add-property': JSXElements.AddPropertyAttributes;
    }
  }
  namespace JSXElements {
    export interface AddPropertyAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  PropertiesPage as PropertiesPage
} from './components/properties/properties-page';

declare global {
  interface HTMLPropertiesPageElement extends PropertiesPage, HTMLStencilElement {
  }
  var HTMLPropertiesPageElement: {
    prototype: HTMLPropertiesPageElement;
    new (): HTMLPropertiesPageElement;
  };
  interface HTMLElementTagNameMap {
    'properties-page': HTMLPropertiesPageElement;
  }
  interface ElementTagNameMap {
    'properties-page': HTMLPropertiesPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'properties-page': JSXElements.PropertiesPageAttributes;
    }
  }
  namespace JSXElements {
    export interface PropertiesPageAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  PropertyDetail as PropertyDetail
} from './components/properties/property-detail';

declare global {
  interface HTMLPropertyDetailElement extends PropertyDetail, HTMLStencilElement {
  }
  var HTMLPropertyDetailElement: {
    prototype: HTMLPropertyDetailElement;
    new (): HTMLPropertyDetailElement;
  };
  interface HTMLElementTagNameMap {
    'property-detail': HTMLPropertyDetailElement;
  }
  interface ElementTagNameMap {
    'property-detail': HTMLPropertyDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'property-detail': JSXElements.PropertyDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface PropertyDetailAttributes extends HTMLAttributes {
      'propertyId'?: string;
      
    }
  }
}


import {
  PageTabs as PropertyTabs
} from './components/properties/property-tabs';

declare global {
  interface HTMLPropertyTabsElement extends PropertyTabs, HTMLStencilElement {
  }
  var HTMLPropertyTabsElement: {
    prototype: HTMLPropertyTabsElement;
    new (): HTMLPropertyTabsElement;
  };
  interface HTMLElementTagNameMap {
    'property-tabs': HTMLPropertyTabsElement;
  }
  interface ElementTagNameMap {
    'property-tabs': HTMLPropertyTabsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'property-tabs': JSXElements.PropertyTabsAttributes;
    }
  }
  namespace JSXElements {
    export interface PropertyTabsAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  AuthInjector as AuthInjector
} from './components/services/auth-injector';

declare global {
  interface HTMLAuthInjectorElement extends AuthInjector, HTMLStencilElement {
  }
  var HTMLAuthInjectorElement: {
    prototype: HTMLAuthInjectorElement;
    new (): HTMLAuthInjectorElement;
  };
  interface HTMLElementTagNameMap {
    'auth-injector': HTMLAuthInjectorElement;
  }
  interface ElementTagNameMap {
    'auth-injector': HTMLAuthInjectorElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'auth-injector': JSXElements.AuthInjectorAttributes;
    }
  }
  namespace JSXElements {
    export interface AuthInjectorAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  DatabaseInjector as DatabaseInjector
} from './components/services/database-injector';

declare global {
  interface HTMLDatabaseInjectorElement extends DatabaseInjector, HTMLStencilElement {
  }
  var HTMLDatabaseInjectorElement: {
    prototype: HTMLDatabaseInjectorElement;
    new (): HTMLDatabaseInjectorElement;
  };
  interface HTMLElementTagNameMap {
    'database-injector': HTMLDatabaseInjectorElement;
  }
  interface ElementTagNameMap {
    'database-injector': HTMLDatabaseInjectorElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'database-injector': JSXElements.DatabaseInjectorAttributes;
    }
  }
  namespace JSXElements {
    export interface DatabaseInjectorAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  FirebaseInjector as FirebaseInjector
} from './components/services/firebase-injector';

declare global {
  interface HTMLFirebaseInjectorElement extends FirebaseInjector, HTMLStencilElement {
  }
  var HTMLFirebaseInjectorElement: {
    prototype: HTMLFirebaseInjectorElement;
    new (): HTMLFirebaseInjectorElement;
  };
  interface HTMLElementTagNameMap {
    'firebase-injector': HTMLFirebaseInjectorElement;
  }
  interface ElementTagNameMap {
    'firebase-injector': HTMLFirebaseInjectorElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'firebase-injector': JSXElements.FirebaseInjectorAttributes;
    }
  }
  namespace JSXElements {
    export interface FirebaseInjectorAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  AddTenant as AddTenant
} from './components/tenants/add-tenant';

declare global {
  interface HTMLAddTenantElement extends AddTenant, HTMLStencilElement {
  }
  var HTMLAddTenantElement: {
    prototype: HTMLAddTenantElement;
    new (): HTMLAddTenantElement;
  };
  interface HTMLElementTagNameMap {
    'add-tenant': HTMLAddTenantElement;
  }
  interface ElementTagNameMap {
    'add-tenant': HTMLAddTenantElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'add-tenant': JSXElements.AddTenantAttributes;
    }
  }
  namespace JSXElements {
    export interface AddTenantAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  TenantsPage as TenantsPage
} from './components/tenants/tenants-page';

declare global {
  interface HTMLTenantsPageElement extends TenantsPage, HTMLStencilElement {
  }
  var HTMLTenantsPageElement: {
    prototype: HTMLTenantsPageElement;
    new (): HTMLTenantsPageElement;
  };
  interface HTMLElementTagNameMap {
    'tenants-page': HTMLTenantsPageElement;
  }
  interface ElementTagNameMap {
    'tenants-page': HTMLTenantsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tenants-page': JSXElements.TenantsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface TenantsPageAttributes extends HTMLAttributes {
      
      
    }
  }
}


import {
  UnitDetail as UnitDetail
} from './components/units/units-detail';

declare global {
  interface HTMLUnitDetailElement extends UnitDetail, HTMLStencilElement {
  }
  var HTMLUnitDetailElement: {
    prototype: HTMLUnitDetailElement;
    new (): HTMLUnitDetailElement;
  };
  interface HTMLElementTagNameMap {
    'unit-detail': HTMLUnitDetailElement;
  }
  interface ElementTagNameMap {
    'unit-detail': HTMLUnitDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'unit-detail': JSXElements.UnitDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface UnitDetailAttributes extends HTMLAttributes {
      'propertyId'?: string;
      'unitId'?: string;
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
